### ISSUE TITLE
(question) Connecting to SFTP? 

### ISSUE THREAD

**Issue by dogboydog** [IBM/zos-node-accessor#10]
Hi, 

I'm trying to connect to  SFTP (I'm able to connect to port 22 via WinSCP so I do know the connection is working ) with this package but I'm not sure exactly what settings I need here: 

You can run this script after modifying by doing `npm install ts-node zos-node-accessor` and then `node -r "ts-node/register" test.ts`:

``` typescript 
const accessor = require("zos-node-accessor");

(async () => {
        try {
            console.log("trying to connect to FTP");
            await new accessor().connect({
                host: "host",
                user: "user",
                password: "pass",
                port: 22,
                secure: true,
                connTimeout: 20000,
                secureOptions: {
                    rejectUnauthorized: false
                }
            });
            console.log("connected successfully");
        }
        catch (err) {
            console.log("Error: " + err);
        } finally {
            console.log("finally");
        }
    }
)();

```

Curiously, I get the "trying to connect to FTP" method and then nothing else.  So it seems no error is thrown and then `finally` is not called either. Not sure if I'm doing something else wrong  but it should probably throw an error if it's not able to connect

**Comment by polyrabbit** [comment]
I'm not familiar with the `async`, `await` stuff, but will give it a try tomorrow.

Here is the code I used to connect to a SFTP endpoint:

```js
new accessor().connect({
                host: "host",
                user: "user",
                password: "pass",
                port: 22,
                secure: true,
                connTimeout: 20000,
                secureOptions: {
                    ca: [ 'CONTENT OF YOUR ROOT CA PEM FILE' ]
                }
            })
```

Please try to export the root ca, fill it to the ca array, and try again see if it works.

The underlying ftp library is https://github.com/mscdex/node-ftp ,  I'm not sure whether it accepts `rejectUnauthorized` or not.

**Comment by dogboydog** [comment]
Ah okay. It's mostly equivalent to the .then() .catch()  syntax but a little easier in my opinion. I tried it that way too and got the same behavior.  I'll try what you suggested.

**Comment by dogboydog** [comment]
Somebody suggested rejectUnauthorized in this issue so it seemed it worked for someone

https://github.com/mscdex/node-ftp/issues/96

**Comment by dogboydog** [comment]
Got it, okay thanks

**Comment by polyrabbit** [comment]
Yes, we will appreciate it if you could send a PR for this feature!

One suggestion beforehand - we'd like to keep it compatible with node v4.x, so I'm afraid you have to stick to the old-fashioned js syntax.

**Comment by polyrabbit** [comment]
Thanks for your help on this package!

One thing I'm wondering - does SFTP work for dataset and JES? I cannot `list` the them on my end:
```
sftp> ls 'MIAOCX.*'
Can't ls: "/u/miaocx/MIAOCX.\\*" not found
sftp> site FILETYPE=JES
Invalid command.
```

**Comment by dogboydog** [comment]
Ah that's too bad. Maybe SFTP is not compatible with the JES interface so the pull request might not be possible? : ( Oh well
