### ISSUE TITLE
Export all defined interfaces for `v2.0.x`

### ISSUE THREAD

**Issue by zFernand0** [IBM/zos-node-accessor#100]
Right now we only export the `./lib/ZosAccessor.d.ts` . However, I believe it will be beneficial if we exported everything inside `interfaces` in order to avoid extenders/developers importing from a package subdirectory

See the example below
```typescript
import { SpoolFile } from "zos-node-accessor/lib/interfaces/SpoolFile";
import { Job, JobStatus } from "zos-node-accessor/lib/interfaces/Job";
import { JobListOption } from "zos-node-accessor/lib/interfaces/JobListOption";
import { JobLogOption } from "zos-node-accessor/lib/interfaces/JobIdOption";
```

More examples can be found in this PR:
- https://github.com/zowe/zowe-cli-ftp-plugin/pull/155

**Comment by std4lqi** [comment]
Hi @zFernand0 , I create PR #101 . Let me know please, if any comments.
