### ISSUE TITLE
Purge / delete job by job id 

### ISSUE THREAD

**Issue by dogboydog** [IBM/zos-node-accessor#11]
It would be cool to have an API  like deleteJob(jobid) to be able to clear spool for a job, or use it to cancel a job that's running

Relevant FTP command is here on Page 136 (PDF page 160): 

https://www-304.ibm.com/servers/resourcelink/svc00100.nsf/pages/zosv2r3sc273662/$file/halu001_v2r3.pdf

**Comment by polyrabbit** [comment]
Hi Chris, I also implemented this API in PR #12 , could you help to verify it? it seems I'm not authorized to delete any job on my server.

**Comment by dogboydog** [comment]
Sure, let me try it out

**Comment by dogboydog** [comment]
deleteJob worked like a charm for me : )  

Well I wasn't able to delete a TSU type job for some reason but was able to delete a normal job with ID starting `JOB`

**Comment by polyrabbit** [comment]
Yeah! case closed.
