### ISSUE TITLE
Create data set via FTP

### ISSUE THREAD

**Issue by dogboydog** [IBM/zos-node-accessor#15]
Hello!  Thanks again for all the changes you've added so far

I know there is a preset JCL way to create data sets with this package, but it doesn't work for me because of the job card. In general, unless you allow the user to specify their own job card, I think preset JCL probably won't work for them because they may have different requirements for their job card such as specifying their own account number, different job or message class etc. 

Page 94  (118 of PDF) describes how to programatically create a new data set. If there was an API that allowed you to specify all the values in the table that'd be awesome
https://www-304.ibm.com/servers/resourcelink/svc00100.nsf/pages/zosv2r3sc273662/$file/halu001_v2r3.pdf

**Comment by polyrabbit** [comment]
Hi @dogboydog , PR #19 also introduces a new api `allocateDataset`:

Usage:
```js
connection.allocateDataset('ABC.DEF', {'LRECL': 80, 'RECFM': 'FB', 'BLKSIZE': 320})
```

Please have a try, thanks!

**Comment by dogboydog** [comment]
Too cool. Can't wait to try thanks

**Comment by dogboydog** [comment]
I did try it -- no error was thrown but it's not showing up in list data set results so it seems like it's not getting created. If it works for you maybe we can still merge it in and I can try it more later. Sorry, my official time to work on the plugin is over so I have to use personal time here and there to try these things out. I appreciate you making the changes

**Comment by dogboydog** [comment]
Thanks. Good point about the quotes, maybe they are being created but not with the name I expect. I will check that out

**Comment by dogboydog** [comment]
Thanks - I see that the data set is indeed being created so the API is working for me. Thanks for the tip, silly of me to forget the quotes. Is there a way to specify DSORG in the FTP API and create a PDS data set?

**Comment by polyrabbit** [comment]
Great, I'm glad it also works on your end.

For the PDS dataset, I think you can set `PDSTYPE=PDS` to create one, but I don't know if there is a convenient way to list a PDS dataset.
