### ISSUE TITLE
Issue unix commands via FTP

### ISSUE THREAD

**Issue by dogboydog** [IBM/zos-node-accessor#16]
Had no idea this was possible but apparently you can issue USS commands via FTP. I think it would be cool to have this even though telnet and ssh could be used instead, because then users of this package could have one configuration that they use for JES, USS, and data set access.

I'm curious to see what return values it gives - hopefully the stdout and stderr separated as well as the exit code? Thanks for all the enhancements. I hope I get to show you what I'm doing with them soon and you could install it and try it out 

page 163 (188 of PDF) 

https://www-304.ibm.com/servers/resourcelink/svc00100.nsf/pages/zosv2r3sc273662/$file/halu001_v2r3.pdf

**Comment by dogboydog** [comment]
I tried to code it up myself but couldn't get it to work with `.site("!" + command)`

I got this output. 
```
Unrecognized parameter '!' on SITE command.
Unrecognized parameter 'ls' on SITE command.
SITE command was accepted
Successfully issued USS command ls

```
Is there a different API I should be using to issue "FTP subcommands"? I was able to use ! through the FTP cli.

**Comment by polyrabbit** [comment]
I'm not sure if there is any way to issue a shell command to the **remote** host, but doesn't the `!` issues command to the **local** host?

Here is the result from my Mac:

```bash
ftp> !uname
Darwin
```

**Comment by dogboydog** [comment]
Ah dang. You are right sorry. Thanks for the clarification
