### ISSUE TITLE
Allow owner parameter on list jobs

### ISSUE THREAD

**Issue by dogboydog** [IBM/zos-node-accessor#18]
It would be cool if users could specify an owner when listing jobs so that they could view jobs under different user IDs (if allowed by security)

**Comment by polyrabbit** [comment]
Please see #19 

Usage:
```js
listJobs({jobName: 'TSU*', owner: 'name*', status: 'output'})
```

Build the query condition at your will.

**Comment by dogboydog** [comment]
Nice! Thanks for the changes
