### ISSUE TITLE
Provide total size on streams

### ISSUE THREAD

**Issue by dogboydog** [IBM/zos-node-accessor#2]
Hi, 

This package is really neat! I've been messing around with it and got some cool stuff done.  

As an enhancement, I was wondering if it's possible to determine the total size in bytes of a file / data set when calling APIs like  `getDataset`? Not sure if the underlying ftp has any way to access that information but it would be cool to be able to provide progress bars / download estimates using this package. If it's possible to determine the size, it could be injected into a custom field of the `ReadableStream`

**Comment by polyrabbit** [comment]
Hi @dogboydog , thanks for the feedback - a quick experiment shows it may not be easy to get the accurate size of a dataset via ftp, here is the string returned by the underlying ftp:

```
Volume Unit    Referred Ext Used Recfm Lrecl BlkSz Dsorg Dsname
XRFS96 3390   2018/05/15  1   15  FB    1024  4096  PS    SAMPLE.JSON
...
```

And the information we can get - `SAMPLE.JSON` used `15` tracks, its record size is `1024` and block size is `4096`.

Deducing from the track size, we can see it uses `15*55*1024=844800bytes`, while the actual size is `497749bytes`, so with the basic information given by ftp, we can only get the upper limit of a dataset.

We will see if there are any way to twist ftp to return more information, stay tuned :)

**Comment by std4lqi** [comment]
User can estimate the dataset size by multiplying `Used` tracks with track size of 56,664 bytes. The estimated size is usually larger, since dataset allocates space by primary/secondary space with allocation or extension.
