### ISSUE TITLE
Does queryJob(jobName,jobId) only look in the job list under one owner name?

### ISSUE THREAD

**Issue by CamvuPham** [IBM/zos-node-accessor#29]
Hello, **zos-node-accessor** authors. Thank you very much for this amazing tool.

Allow me to ask for your help. Does **queryJob**(jobName,jobId) only look in the job list under one owner name.

For example, my TSO IS is PHAMCT. There is output job I need to search for under owner name AUTOIPL (a virtual user). Here is the output list (Job Name - Job Id - Owner):
AUTOIPLW JOB08820 PHAMCT 
AUTOIPL  STC08821 AUTOIPL

**queryJob**(AUTOIPL,STC08821) cannot find this output. Is it because the output is under another owner's name?

**Comment by polyrabbit** [comment]
Hi CamvuPham. Thanks for reaching out.

Actually, the parameter `jobName` can be a string as well as an object. It's treated the same way as the `jobName` parameter of [list-jobs](https://github.com/IBM/zos-node-accessor#list-jobs):

- Case `string` - it presumes you are querying a job whose name matches the string under the **the owner's name**.
- Case `object` - A more flexible filtering condition, whose valid keys are:
  * jobName: specify a JES job name, it can contain a wildcard (*)
  * owner: specify a JES job owner, it can contain a wildcard (*)
  * status: specify a JES job status, eg. ALL, OUTPUT

To answer your question - yes, it will only look for the job under one owner's name if you pass a `string`. So in your case, I think passing `{jobName: 'AUTOIPL', owner: 'AUTOIPL'}` will work.

BTW, we will fix the doc to clarify those two cases.

**Comment by std4lqi** [comment]
The document is updated to be more clear now.


#### Query job

`queryJob(jobNameOrOption, jobId)` -  Query job status identified by job name and job id. The following parameters are accepted. _(Deprecated, use `getJobStatus` for more details.)_

##### Parameter

* jobName - _string_ -  Name of the job.
* jobId - _string_ -  Id of the job.

##### Parameter

 * option - _object_ - Option which contains:
   *  jobName - _string_ - specify a JES job name, which is optional and can contain a wildcard (*)
   *  jobId - _string_ - specify a JES job ID, which is required
   *  owner - _string_ - specify a JES job owner, which is optional and can contain a wildcard (*)

**Comment by phamct** [comment]
@polyrabbit @std4lqi Thank you so very much for your answers. You are great supporters!
