### ISSUE TITLE
Documentation of stream parameter incorrect? 

### ISSUE THREAD

**Issue by dogboydog** [IBM/zos-node-accessor#3]
Hey sorry to keep making issues but I'm messing around with this package pretty heavily. Still enjoying it

I noticed this parameter in the README: 

```
stream - boolean (default: false) - true if you want to read a full dataset into memory (in Buffer), otherwise you get a ReadableStream.
```
When I getDataset, the behavior seems to be the opposite of what is described here.  Specifying `true` gives me back a stream .  I didn't check what happens when you don't specify stream.  If you confirm this is wrong I can  submit a PR for the README

**Comment by polyrabbit** [comment]
Hi, thanks for your report, I can confirm this is an error in our document 😢 

I'll appreciate if you can submit a PR to fix the docs!
