### ISSUE TITLE
Documentation refers to var Client = require('zosAccessor');

### ISSUE THREAD

**Issue by IgorTodorovskiIBM** [IBM/zos-node-accessor#30]
But should it not be: `var Client = require('zos-node-accessor');`?

**Comment by premsank** [comment]
hi Igor, that is what even I coded in my node JS program.
var Client = require('zos-node-accessor');

**Comment by IgorTodorovskiIBM** [comment]
I'm referring to the example here: https://github.com/IBM/zos-node-accessor

```
var Client = require('zosAccessor');

var c = new Client();
// connect to localhost:21 as hansome using password
c.connect({user: 'myname', password:'mypassword'})
  .then(function(connection) {
    // here connection equals to outer c
  })
  .catch(function(err) {
    // handle error
  });
```

**Comment by std4lqi** [comment]
Thanks for the good catching! I fixed the module name in the commit of https://github.com/IBM/zos-node-accessor/commit/8daad509e9b44b0335ee3c4b73b65d205240664e
