### ISSUE TITLE
zos-node-accessor doesn't work well with Node.js version 10+

### ISSUE THREAD

**Issue by phamct** [IBM/zos-node-accessor#34]
Dear developers, this can be considered a report to you. We had problem getting z/Os job output with zos-node-accessor and found out that it was because of upgrading Node.js version from v8 to v10.

Switching back to Node.js v8, things work again. Yet our team wish to let you know about this case in case you have solution for it in the future.

We also found document informing that IBM SDK for Node.js is supporting up to Node.js version 8. We guess zos-node-accessor might be limited by that. 

zos-node-accessor has been a key part in our project and we would like to thank you again for this tool. Thank you.

**Comment by std4lqi** [comment]
Many thanks for your reporting this problem to us! 

We mostly focuses on Node.JS version 6 and 8 with the efforts aligned with IBM SDK for Node.JS on z/OS. I suppose your Node.JS app doesn't run on z/OS, right? 

I'm afraid we will not fully support version 10 in near future, but can try to fix any specific issue found on version 10.

Thanks again for your feedback! We're pleased to know zos-node-accessor does help to other z/OS projects.

**Comment by phamct** [comment]
@std4lqi Thank you for your response. Our Node.JS app is running in Windows, Ubuntu (Linux for z), and MacOS, using zos-node-accessor to connect to z/OS systems. zos-node-accessor has been working wonderfully.
Best wishes to you and the team.

**Comment by chrishham** [comment]
You can also use [zos-utils](https://www.npmjs.com/package/zos-utils) npm package  , which supports NodeJS versions up to **V12.04.0**.

**Comment by tiantn** [comment]
@phamct Hi phamct! The tool works well with node v10.15.3 in my environment and no ploblems found. Could you post the problem details if you convenient? Thank you very much!

**Comment by tiantn** [comment]
I also tried the node v12.13.0. It works well.

**Comment by std4lqi** [comment]
Hi, @phamct  

The issue related to Node.js version 10+ was fixed v1.0.5. I close this issue. And please let us know, if any other problem. Thanks!
