### ISSUE TITLE
Can't access host from Linux

### ISSUE THREAD

**Issue by cabrerachaparro** [IBM/zos-node-accessor#37]
Hello,
I am trying to access the host from my machine with Linux (Fedora 30) but I get the following issue

`error { Error: PASS command failed
    at makeError (/home/dcabrera/stfmvs1/node_modules/ftp/lib/connection.js:1067:13)
    at Parser.<anonymous> (/home/dcabrera/stfmvs1/node_modules/ftp/lib/connection.js:113:25)
    at Parser.emit (events.js:198:13)
    at Parser._write (/home/dcabrera/stfmvs1/node_modules/ftp/lib/parser.js:59:10)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at Parser.Writable.write (_stream_writable.js:299:11)
    at Socket.ondata (/home/dcabrera/stfmvs1/node_modules/ftp/lib/connection.js:273:20)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12) code: 530 }
`
However it worked when I run it from the host (USS).

This is the code

`var Client = require('zos-node-accessor');

var USERNAME = process.env.USERNAME || 'user';
var PASSWD = process.env.PASSWD  || 'pwd';
var HOST = process.env.HOST || 'host.com';

var c = new Client();

c.connect({user: USERNAME, password: PASSWD, host: HOST})
    .then(function(connection) {
        console.log('Connection successfuly');
        c.getDataset('HLQ.CONTROL.PARM','ascii')
            .then(function(jclBuffer){
                console.log(jclBuffer.toString());
            })
            .catch(function(err){
                console.log('error', err)
            });
    })
    .catch(function(err){
        console.log('error', err);
`

Thanks

**Comment by std4lqi** [comment]
It looks like kind of FTP connection error. Could you try whether you can connect z/OS remotely with the regular FTP client from Linux? Thanks!

**Comment by cabrerachaparro** [comment]
Yes, I can connect

**230 USER is logged on.  Working directory is "USER.".
Remote system type is MVS.
ftp>**

**Comment by std4lqi** [comment]
Can I know the Node.JS version on Linux? Or you can try Node.JS 8.x or even 6.x?  If it still failed, we may try to see what the exact FTP error code is.

Go the `/home/dcabrera/stfmvs1/node_modules/ftp/lib/connection.js`, and print code at the line 110.
```
 109   this._parser.on('response', function(code, text) {
 110     var retval = code / 100 >> 0;
 111     if (retval === RETVAL.ERR_TEMP || retval === RETVAL.ERR_PERM) {
 112       if (self._curReq)
 113         self._curReq.cb(makeError(code, text), undefined, code);
 114       else
 115         self.emit('error', makeError(code, text));
 116     } else if (self._curReq)
 117       self._curReq.cb(undefined, text, code);
```

And the error messages can be found around line 33.

```
  33     /*ERRORS = {
  34       421: 'Service not available, closing control connection',
  35       425: 'Can\'t open data connection',
  36       426: 'Connection closed; transfer aborted',
  37       450: 'Requested file action not taken / File unavailable (e.g., file busy)',
  38       451: 'Requested action aborted: local error in processing',
  39       452: 'Requested action not taken / Insufficient storage space in system',

```

**Comment by cabrerachaparro** [comment]
The node version is v10.16.3 however I installed version v8.16.1 and I get the same error.
According to the message error code 530 means 

> 'Not logged in'

**Comment by std4lqi** [comment]
The 530 means 

> The login to the user ID on the server system is rejected.

https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.2.0/com.ibm.zos.v2r2.cs3cod0/ftp530-20.htm

Could you print user/password for double check? 

I'm also thinking about whether the problem is relevant to encoding. Could you put password in JS code to see whether it works?

You may also want to check this

https://stackoverflow.com/questions/33015569/ftpclient-login-method-replies-530-pass-command-failed-from-the-server

**Comment by cabrerachaparro** [comment]
The problem was related to the username. It was taking the Linux username and not host name.
Thank you for your support.
