### ISSUE TITLE
List jobs by job ID 

### ISSUE THREAD

**Issue by dogboydog** [IBM/zos-node-accessor#4]
Is it possible to list jobs by job ID rather than job name? That is, basically locate the details of one job by job ID?  In case I am trying to locate a job which I don't know the name of such as one returned by `submitJCL`?

Since we found a way to list DDs and other job info in #6,  It'd be nice to return job name, return code etc. from a job using the same underlying FTP command

Thank you

**Comment by polyrabbit** [comment]
Yes, I agree, identifying a job just by `job id` sounds reasonable.

However, I'm not a z expert - not knowing how to find a job by id without restricting the scope by job name first. It seems the default jobname pattern is `HLQ*`, and querying other job id under this scope results in nothing.

Do you know anyway to tell JES not adding the jobname restriction when searching for a job id?

**Comment by dogboydog** [comment]
What about the DIR command on Page 133 (157 of the pdf)

**Comment by polyrabbit** [comment]
Ah, I just find a work-around - setting JESJOBNAME to `*` makes JES searches for job id under all the names, will come to you later if this indeed works!

**Comment by dogboydog** [comment]
Any way I could try a version of this if you're close like trying a @next package? Sorry not trying to rush you but would help with some of my commands that I'm working on this week. Also let me know if you want to talk more about your Brightside install problems

**Comment by polyrabbit** [comment]
Sorry for the delay, I'll publish one version tomorrow (China time) 🤗

**Comment by dogboydog** [comment]
No apologies necessary, I appreciate you making changes for me. Helps me out a lot

**Comment by polyrabbit** [comment]
I added a new api `getJobStatus`, it parses the `list` response, returning `job name`, `return code`, `spool file list` etc.

After getting the `spool file list`, you can invoke `getJobLog(jobName, jobId, spoolFileIndex)` to get the content of a specific spool file (set  `spoolFileIndex` to `"x"` to get all spool file concatenated together).

See PR #12 for more details, any suggestion?

**Comment by dogboydog** [comment]
That is awesome. Is "x" the default so that if you call it with just `getJobLog(jobname, jobid)` it returns you everything? And do you get an array if you specify `x` or the old string version joined with the `!! END OF JES SPOOL FILE !!` message? I was just wondering in case I wanted to get an array of the object version of all spool files

**Comment by dogboydog** [comment]
I guess I could just loop through each index and combine them into an array that way though so it's no big deal

**Comment by polyrabbit** [comment]
1. Yes, `x` is the default.

2. `getJobLog` always returns a raw string - meaning `!! END OF JES SPOOL FILE !!` will be used as the separator when getting all spool files. I hope to keep return value in a consistent format regardless of the input. Do you have any other idea/thought?

3. Yes, you get it. We want to keep `getJobStatus` as lightweight as possible. Here is the workflow :  
> 1. `getJobStatus` to get a list of spool files
> 2. Loop each spool file, and use `getJobLog` to get its content. Or get all spool files using `x` and split it with `!! END OF JES SPOOL FILE !!`, then combine the content with their info.

**Comment by dogboydog** [comment]
Thanks for your response!  And it looks like you can get job status with just jobid which will be great for me!

**Comment by dogboydog** [comment]
Sounds like I can do everything I need with these changes by getting the job status and then looping through each spool file.

**Comment by dogboydog** [comment]
Thanks for introducing the new API! Works great
