### ISSUE TITLE
tls.connect

### ISSUE THREAD

**Issue by trinhhuynguyen** [IBM/zos-node-accessor#47]
I defined the tls options below. It doesn't connect when I set 'secure=true'. Do I need to set 'secure' for tls.connect options.

const options = {

    host: 'xxxx',
    user: 'user1',
    port: 21,
    password: fs.readFileSync(PWfilePath, 'utf8').trim(),
    secure: true,
    secureOptions: { 
        // Necessary only if the server requires client certificate authentication.
        key: fs.readFileSync('client-key.pem'),

        cert: fs.readFileSync('client-crt.pem'),

        // Necessary only if the server uses a self-signed certificate.
        ca: [fs.readFileSync('mes02_cert.pem')],

        // Necessary only if the server's cert isn't for "localhost".
        checkServerIdentity: (servername, crt) => {
            console.log('checkServerIdentity: ', servername);
            if (servername !== crt.subject.CN) {
                throw new Error(`Servername ${servername} does not match CN ${crt.subject.CN}`);
            }
        },
        //debug: {message: 'connect'}
    }
};
 

function MVScommandToNativeSystem(MVScommand, callback) {
    var UserTsoID = options.user;
	client.connect(options)
		.then(function (client) {
			if (client.connected) {			return client;
			} 
			return Q.reject('Failed to connect to', HOST);
		});
	return SubmitMVScommandJob(client, JCLjob, callback);
}

**Comment by std4lqi** [comment]
Hi,

The option `secure` is required. Only `ca` is required for FTP over SSL. CA should contains the root certificate that signs the certificate used by FTP.

```
    var connectionInfo = {
        user: 'user',
        password: 'xxxx',
        host: 'xxxx',
        port: 21,
        secure: true,
        secureOptions: {
            ca: [ fs.readFileSync(CA_FILE) ]
        }
    };
```

**Comment by trinhhuynguyen** [comment]
I set 'rejectUnauthorized:false', and it worked. I guess my CA was a self-signed? 
Also, do you know why this 'checkServerIdentity' never throw the error if I used a wrong server name than the one in the certificate? 

checkServerIdentity: (servername, crt) => {
            if (servername !== crt.subject.CN) {
                throw new Error(`Servername ${servername} does not match CN ${crt.subject.CN}`);
            }
 },

**Comment by std4lqi** [comment]
Oh, yes. If the self-signed certificate, you need set `rejectUnauthorized:false`. We didn't try this `checkServerIdentity` before.  My understanding is since you allow unauthorized certificate, this check will never be called.

**Comment by trinhhuynguyen** [comment]
Thanks very much. We can close this for now.
