### ISSUE TITLE
uploadDataset gives "Error: Unable to parse PASV server response"

### ISSUE THREAD

**Issue by nishantsood-de** [IBM/zos-node-accessor#79]
The connection seems to be successful but when I use uploadDataset it gives me the error "Error: Unable to parse PASV server response".

Is there a issue?
Is there a way to get complete log?

**Comment by std4lqi** [comment]
Hi, it seems the IP and port for PASV connection are not returned from FTP server correctly. Some questions to understand your problem better.

1. Are you using v1 or v2? 
2. Any problem with `listDataset` or `downloadDataset`?
3. Any problem with uploading dataset using ftp tool like FileZilla? 

Thanks!

**Comment by nishantsood-de** [comment]
The issue was with my code. The previous connection was not closed properly.
