### ISSUE TITLE
downloadDataset : missing site params in v2

### ISSUE THREAD

**Issue by oseam87** [IBM/zos-node-accessor#88]
In v1, getDataSet accepts other site params (sbd for example), this is not possible in v2 with downloadDataset .

**Comment by std4lqi** [comment]
Hi @oseam87, site params is not supported in v2 now. Can I know whether you are using v1 and planing to move v2? Or you are using v2? Thanks!

**Comment by oseam87** [comment]
I'm using v2. Disregard this issue, I think I can just call the "site" method with the conversions parameters just before calling downloadDataset.

**Comment by std4lqi** [comment]
Thanks, @oseam87 !  Good to try `site` before `downloadDataset`. It makes sense to me to add site param as parameter of `downloadDatase`. Will add it soon.
