### ISSUE TITLE
Trailing blanks

### ISSUE THREAD

**Issue by oseam87** [IBM/zos-node-accessor#96]
Hello,

I'd like to retrieve text files without the trailing blanks, which is the default behavior according to the IBM documentation, but in the _download_ method, the paramater "TRAILINGBLANKS" is always set:

`let site = 'FILETYPE=SEQ TRAILINGBLANKS ' + sbsendeol;`

There is no way to override this as far as I know (I tried setting it to false in the siteParams but it didn't work).

Is there any reason this parameter is always set ?

Thank you.

**Comment by std4lqi** [comment]
Hi @oseam87, yes, the `TRAILINGBLANKS` is always set now. We can consider to add `ASCII_NO_TRAILING_BLANKS` as new transferMode option.

**Comment by oseam87** [comment]
Thanks, as long as there is an option to choose! Is there a particular reason it is always set? It makes sense to not include trailing spaces for FB datasets (the difference in size can be a few MB!).

**Comment by std4lqi** [comment]
Some historical reason that we needed the trailing blanks when we developed it for our project a couple of years. We're working on `ASCII_NO_TRAILING_BLANKS` recently.

**Comment by std4lqi** [comment]
Fixed in 1.0.16.
